apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: filohero/hello-world-app:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.7"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-app
spec:
  selector:
    app: hello-world-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
