name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Minikube
      run: |
        sudo apt update
        sudo apt install -y conntrack
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=docker
        kubectl config use-context minikube

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Code Quality Check
      run: |
        npm install -g eslint
        eslint .

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world-app .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-app

    - name: Security Scans
      run: |
        sudo apt-get install wget
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy
        trivy --exit-code 0 ${{ secrets.DOCKER_USERNAME }}/hello-world-app
        dependency-check . --project "HelloWorld" --scan .

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yml

    - name: Test Deployment
      run: |
        curl http://localhost:3000/