name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Minikube
      run: |
        sudo apt update
        sudo apt install -y conntrack
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=docker
        kubectl config use-context minikube

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Install Clair
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/quay/clair/releases/download/v4.3.0/clair-v4.3.0-linux-amd64.tar.gz
        tar -xzf clair-v4.3.0-linux-amd64.tar.gz
        sudo mv clair /usr/local/bin

    - name: Code Quality Check
      run: |
        npm install -g eslint
        eslint .

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world-app .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-app

    - name: Security Scans
      run: |
        clair-scanner -c http://localhost:6060 ${{ secrets.DOCKER_USERNAME }}/hello-world-app
        dependency-check --project "node-hello" --scan .

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yml

    - name: Test Deployment
      run: |
        curl http://localhost:3000/